/**
 * English-string -> translation-key aliases for values referenced dynamically
 * (enum statuses, label arrays, static page content). Generated during the
 * next-i18next migration. New code should use the namespaced keys directly.
 */
export const LEGACY_UI_KEYS: Record<string, string> = {
	"Home": "nav.home",
	"Study": "nav.study",
	"Work": "nav.work",
	"Visa": "nav.visa",
	"Help": "nav.help",
	"Map": "nav.map",
	"My Page": "nav.myPage",
	"Login / Register": "nav.loginRegister",
	"Notifications": "nav.notifications",
	"Mark all read": "nav.markAllRead",
	"All caught up!": "nav.allCaughtUp",
	"Agency": "auth.agency",
	"Users": "auth.users",
	"User": "auth.user",
	"Register": "auth.register",
	"Your global": "auth.yourGlobal",
	"migration": "auth.migration",
	"journey starts.": "auth.journeyStarts",
	"Connect with verified agencies, explore services in 30+ countries, and manage your entire application in one place.": "auth.connectWithVerifiedAgenciesExplore",
	"Verified & trusted migration agencies": "auth.verifiedTrustedMigrationAgencies",
	"Services across 30+ countries worldwide": "auth.servicesAcross30CountriesWorldwide",
	"Secure documents & application tracking": "auth.secureDocumentsApplicationTracking",
	"Study, work, travel and visa services": "auth.studyWorkTravelAndVisa",
	"Welcome back": "auth.welcomeBack",
	"Sign in to your account": "auth.signInToYourAccount",
	"Create your account": "auth.createYourAccount",
	"Sign in": "auth.signIn",
	"Phone number or email": "auth.phoneNumberOrEmail",
	"Password": "auth.password",
	"Signing in...": "auth.signingIn",
	"No account?": "auth.noAccount",
	"Create one": "auth.createOne",
	"Apply for services": "auth.applyForServices",
	"Manage services": "auth.manageServices",
	"First name": "auth.firstName",
	"Last name": "auth.lastName",
	"Phone number": "auth.phoneNumber",
	"Creating...": "auth.creating",
	"Create agency account": "auth.createAgencyAccount",
	"Create account": "auth.createAccount",
	"Already registered?": "auth.alreadyRegistered",
	"Admin sign in": "auth.adminSignIn",
	"Are you an admin?": "auth.areYouAnAdmin",
	"Admin panel": "auth.adminPanel",
	"User account?": "auth.userAccount",
	"User sign in": "auth.userSignIn",
	"Sizning hisobingiz bloklangan. Qo'llab-quvvatlash bilan bog'laning.": "auth.sizningHisobingizBloklanganQollabQuvvatlash",
	"Telefon/email yoki parol noto'g'ri.": "auth.telefonEmailYokiParolNotogri",
	"Bu telefon raqam allaqachon ro'yxatdan o'tgan.": "auth.buTelefonRaqamAllaqachonRoyxatdan",
	"Ro'yxatdan o'tishda xato. Qayta urinib ko'ring.": "auth.royxatdanOtishdaXatoQaytaUrinib",
	"Your Journey to a": "home.yourJourneyToA",
	"New World": "home.newWorld",
	"Starts Here": "home.startsHere",
	"Connect with 500+ trusted immigration and travel agencies. Start your journey to study, work, or explore the world today.": "home.connectWith500TrustedImmigration",
	"Explore Agencies": "home.exploreAgencies",
	"Browse Services": "home.browseServices",
	"Search services, agencies...": "home.searchServicesAgencies",
	"All Countries": "home.allCountries",
	"Simple Process": "home.simpleProcess",
	"How It Works": "home.howItWorks",
	"Three simple steps to launch your global journey with confidence.": "home.threeSimpleStepsToLaunch",
	"Browse & Discover": "home.browseDiscover",
	"Explore hundreds of verified agencies and thousands of services. Filter by country, type, rating, and price to find the perfect match.": "home.exploreHundredsOfVerifiedAgencies",
	"Apply Online": "home.applyOnline",
	"Submit your application in minutes. Upload documents and track your status in real-time directly from your personal dashboard.": "home.submitYourApplicationInMinutes",
	"Start Your Journey": "home.startYourJourney",
	"Get approved and begin your international adventure. Our partner agencies provide full support every step of the way.": "home.getApprovedAndBeginYour",
	"What We Offer": "home.whatWeOffer",
	"Explore Our Services": "home.exploreOurServices",
	"Everything you need to make your international journey smooth and successful.": "home.everythingYouNeedToMake",
	"Explore": "home.explore",
	"Join GMP Today": "home.joinGmpToday",
	"Ready to Start Your": "home.readyToStartYour",
	"Global Journey?": "home.globalJourney",
	"Whether you're a traveler seeking new horizons or an agency wanting to reach thousands of clients — GMP is the platform where opportunity meets ambition.": "home.whetherYoureATravelerSeeking",
	"Get Started Free": "home.getStartedFree",
	"Browse Agencies": "home.browseAgencies",
	"Top Rated Agencies": "home.topRatedAgencies",
	"Verified and trusted partners for your migration journey": "home.verifiedAndTrustedPartnersFor",
	"View All": "home.viewAll",
	"Popular Services": "home.popularServices",
	"Hand-picked top-rated services to get you started": "home.handPickedTopRatedServices",
	"120+ Programs": "home.120Programs",
	"200+ Opportunities": "home.200Opportunities",
	"80+ Packages": "home.80Packages",
	"150+ Services": "home.150Services",
	"Top universities in Europe, Asia, and America. Scholarships and full support included.": "home.topUniversitiesInEuropeAsia",
	"Find your dream job overseas. Work permits, job placement, and relocation assistance.": "home.findYourDreamJobOverseas",
	"Explore the world with curated travel packages. Hotels, tours, and experiences.": "home.exploreTheWorldWithCurated",
	"Fast, reliable visa processing. Tourist, student, and work visas worldwide.": "home.fastReliableVisaProcessingTourist",
	"Trusted migration and travel agency.": "home.trustedMigrationAndTravelAgency",
	"Verified agencies": "home.verifiedAgencies",
	"Verified Partners": "home.verifiedPartners",
	"Top 5 Agencies": "home.top5Agencies",
	"The highest-rated agencies trusted by the GMP community.": "home.theHighestRatedAgenciesTrusted",
	"Your journey to global opportunities": "home.yourJourneyToGlobalOpportunities",
	"From first search to final destination — GMP guides you every step of the way.": "home.fromFirstSearchToFinal",
	"Search Services": "home.searchServices",
	"Browse hundreds of verified visa, study, work, and travel services from trusted agencies worldwide.": "home.browseHundredsOfVerifiedVisa",
	"Connect with Agencies": "home.connectWithAgencies",
	"Reach out to verified immigration agencies, ask questions, and compare service offerings in real time.": "home.reachOutToVerifiedImmigration",
	"Submit Application": "home.submitApplication",
	"Apply directly through GMP. Track your application status, upload documents, and get real-time updates.": "home.applyDirectlyThroughGmpTrack",
	"Achieve Your Goal": "home.achieveYourGoal",
	"Complete your journey — study abroad, start a new career, or explore the world with confidence.": "home.completeYourJourneyStudyAbroad",
	"Search services by country or type...": "home.searchServicesByCountryOr",
	"Work Permit": "home.workPermit",
	"Travel Package": "home.travelPackage",
	"Visa Service": "home.visaService",
	"United Kingdom": "home.unitedKingdom",
	"Germany": "home.germany",
	"Japan": "home.japan",
	"Canada": "home.canada",
	"Popular": "home.popular",
	"New": "home.new",
	"Fast": "home.fast",
	"Success rate": "home.successRate",
	"Clients served": "home.clientsServed",
	"Destination countries": "home.destinationCountries",
	"Explore all services": "home.exploreAllServices",
	"Trusted Agencies": "home.trustedAgencies",
	"Countries Covered": "home.countriesCovered",
	"Happy Users": "home.happyUsers",
	"Services Available": "home.servicesAvailable",
	"Explore Destinations": "home.exploreDestinations",
	"Popular Destinations": "home.popularDestinations",
	"Discover opportunities in the world's most sought-after destinations for study, work, and travel.": "home.discoverOpportunitiesInTheWorlds",
	"United States": "home.unitedStates",
	"South Korea": "home.southKorea",
	"Australia": "home.australia",
	"AI Assistant": "ai.aIAssistant",
	"Ask AI": "ai.askAi",
	"Ask about visas, agencies, or services...": "ai.askAboutVisasAgenciesOr",
	"Hi! Ask me anything about studying, working, or traveling abroad.": "ai.hiAskMeAnythingAbout",
	"Thinking...": "ai.thinking",
	"Something went wrong. Please try again.": "ai.somethingWentWrongPleaseTry",
	"Scroll": "agency.scroll",
	"Search": "agency.search",
	"Agencies": "agency.agencies",
	"Services": "agency.services",
	"Average rating": "agency.averageRating",
	"Reviews": "agency.reviews",
	"Cancel": "agency.cancel",
	"No agencies found": "agency.noAgenciesFound",
	"reviews": "agency.reviews2",
	"Views": "agency.views",
	"Likes": "agency.likes",
	"Verified agency marketplace": "agency.verifiedAgencyMarketplace",
	"Find the right migration": "agency.findTheRightMigration",
	"agency with confidence": "agency.agencyWithConfidence",
	"Compare trusted agencies by reviews, services, countries, and profile details before you start your journey.": "agency.compareTrustedAgenciesByReviews",
	"Search by agency name or country...": "agency.searchByAgencyNameOr",
	"Agencies listed": "agency.agenciesListed",
	"Countries covered": "agency.countriesCovered",
	"Recommended first": "agency.recommendedFirst",
	"Top verified agencies": "agency.topVerifiedAgencies",
	"Agency directory": "agency.agencyDirectory",
	"Results for": "agency.resultsFor",
	"All verified agencies": "agency.allVerifiedAgencies",
	"agencies found": "agency.agenciesFound",
	"Verified only": "agency.verifiedOnly",
	"Map View": "agency.mapView",
	"Most services": "agency.mostServices",
	"Best rating": "agency.bestRating",
	"Newest agencies": "agency.newestAgencies",
	"Try another keyword or clear the current search.": "agency.tryAnotherKeywordOrClear",
	"Clear search": "agency.clearSearch",
	"Agency not found": "agency.agencyNotFound",
	"This profile may have been removed or is no longer available.": "agency.thisProfileMayHaveBeen",
	"Back to agencies": "agency.backToAgencies",
	"Verified agency": "agency.verifiedAgency",
	"About": "agency.about",
	"About this agency": "agency.aboutThisAgency",
	"No description has been added for this agency yet.": "agency.noDescriptionHasBeenAdded",
	"Operating countries": "agency.operatingCountries",
	"No operating countries listed yet.": "agency.noOperatingCountriesListedYet",
	"Client reviews": "agency.clientReviews",
	"No comment provided.": "agency.noCommentProvided",
	"No reviews yet.": "agency.noReviewsYet",
	"Contact agency": "agency.contactAgency",
	"Use the available channels or start a private conversation.": "agency.useTheAvailableChannelsOr",
	"No public contact details yet.": "agency.noPublicContactDetailsYet",
	"This is your agency": "agency.thisIsYourAgency",
	"Send message": "agency.sendMessage",
	"Message sent!": "agency.messageSent",
	"Send another": "agency.sendAnother",
	"Open messages": "agency.openMessages",
	"Write your message to this agency...": "agency.writeYourMessageToThis",
	"Sending...": "agency.sending",
	"Following": "agency.following",
	"Follow agency": "agency.followAgency",
	"Unfollowed": "agency.unfollowed",
	"Following agency!": "agency.followingAgency",
	"likes": "agency.likes2",
	"views": "agency.views2",
	"Destination": "service.destination",
	"Price": "service.price",
	"No services found": "service.noServicesFound",
	"Global": "service.global",
	"Top ranked": "service.topRanked",
	"Curated migration services": "service.curatedMigrationServices",
	"Study Abroad Programs": "service.studyAbroadPrograms",
	"Work Abroad Opportunities": "service.workAbroadOpportunities",
	"Travel Packages": "service.travelPackages",
	"Explore services for every step of your journey": "service.exploreServicesForEveryStep",
	"Find the best study abroad programs tailored to your goals and destination.": "service.findTheBestStudyAbroad",
	"Discover work abroad opportunities matched to your skills and career goals.": "service.discoverWorkAbroadOpportunitiesMatched",
	"Explore travel packages and guided tours around the world.": "service.exploreTravelPackagesAndGuided",
	"Professional visa assistance for every country and purpose.": "service.professionalVisaAssistanceForEvery",
	"Search visa, study, work, and travel services by price, destination, and popularity.": "service.searchVisaStudyWorkAnd",
	"Search by service name or destination...": "service.searchByServiceNameOr",
	"Services available": "service.servicesAvailable",
	"Service categories": "service.serviceCategories",
	"Browse all": "service.browseAll",
	"Documentation": "service.documentation",
	"Education": "service.education",
	"Career": "service.career",
	"Explore world": "service.exploreWorld",
	"Filters": "service.filters",
	"Best rated": "service.bestRated",
	"Newest first": "service.newestFirst",
	"Reset filters": "service.resetFilters",
	"Service directory": "service.serviceDirectory",
	"Available services": "service.availableServices",
	"services found": "service.servicesFound",
	"Verified partners": "service.verifiedPartners",
	"Agencies for this service": "service.agenciesForThisService",
	"Recommended agencies": "service.recommendedAgencies",
	"Verified agencies offering this category.": "service.verifiedAgenciesOfferingThisCategory",
	"Verified agencies across all service categories.": "service.verifiedAgenciesAcrossAllService",
	"No verified agencies found for this category yet.": "service.noVerifiedAgenciesFoundFor",
	"Try another keyword, service type, or price range.": "service.tryAnotherKeywordServiceType",
	"Clear filters": "service.clearFilters",
	"Service not found": "service.serviceNotFound",
	"This service may no longer be available.": "service.thisServiceMayNoLonger",
	"Back to services": "service.backToServices",
	"A trusted service designed to support your migration journey.": "service.aTrustedServiceDesignedTo",
	"Service price": "service.servicePrice",
	"Processing": "service.processing",
	"Processing time depends on the case.": "service.processingTimeDependsOnThe",
	"Application limit reached": "service.applicationLimitReached",
	"Apply now": "service.applyNow",
	"Service details": "service.serviceDetails",
	"No description provided.": "service.noDescriptionProvided",
	"Eligible countries": "service.eligibleCountries",
	"Write a review": "service.writeAReview",
	"Share your experience...": "service.shareYourExperience",
	"Submit review": "service.submitReview",
	"Application submitted successfully!": "service.applicationSubmittedSuccessfully",
	"Please write a comment": "service.pleaseWriteAComment",
	"Your review was sent for moderation": "service.yourReviewWasSentFor",
	"Failed to submit review": "service.failedToSubmitReview",
	"View Profile": "map.viewProfile",
	"Agency locations worldwide": "map.agencyLocationsWorldwide",
	"Find agencies": "map.findAgencies",
	"near you": "map.nearYou",
	"Browse our global network of verified migration agencies on the interactive map.": "map.browseOurGlobalNetworkOf",
	"Cities": "map.cities",
	"Add agency data": "map.addAgencyData",
	"Set lat/lng in agency profiles to see them here": "map.setLatLngInAgency",
	"Top-rated agencies appear on the map": "map.topRatedAgenciesAppearOn",
	"Global network": "map.globalNetwork",
	"Agencies across multiple countries": "map.agenciesAcrossMultipleCountries",
	"Explore full map": "map.exploreFullMap",
	"Loading map...": "map.loadingMap",
	"Open interactive map": "map.openInteractiveMap",
	"Search agencies, cities...": "map.searchAgenciesCities",
	"All countries": "map.allCountries",
	"City...": "map.city",
	"agency": "map.agency",
	"agencies": "map.agencies",
	"on map": "map.onMap",
	"Add latitude and longitude to agency profiles to show them on the map.": "map.addLatitudeAndLongitudeTo",
	"Travel": "mypage.travel",
	"Study Abroad": "mypage.studyAbroad",
	"Work Abroad": "mypage.workAbroad",
	"Visa Services": "mypage.visaServices",
	"Messages": "mypage.messages",
	"Type a message...": "mypage.typeAMessage",
	"Countries": "mypage.countries",
	"Applications": "mypage.applications",
	"Status": "mypage.status",
	"Service": "mypage.service",
	"Rating": "mypage.rating",
	"Approve": "mypage.approve",
	"Reject": "mypage.reject",
	"Service deleted": "mypage.serviceDeleted",
	"Rejected": "mypage.rejected",
	"Approved": "mypage.approved",
	"Bio": "mypage.bio",
	"Nationality": "mypage.nationality",
	"Description": "mypage.description",
	"Website": "mypage.website",
	"Location": "mypage.location",
	"Failed to delete service": "mypage.failedToDeleteService",
	"Submitting...": "mypage.submitting",
	"Processing time": "mypage.processingTime",
	"My account": "mypage.myAccount",
	"Profile": "mypage.profile",
	"Personal details": "mypage.personalDetails",
	"Edit profile": "mypage.editProfile",
	"Click to change photo": "mypage.clickToChangePhoto",
	"Save changes": "mypage.saveChanges",
	"Application center": "mypage.applicationCenter",
	"My applications": "mypage.myApplications",
	"No applications yet.": "mypage.noApplicationsYet",
	"Saved agencies": "mypage.savedAgencies",
	"Following agencies": "mypage.followingAgencies",
	"Not following any agencies yet.": "mypage.notFollowingAnyAgenciesYet",
	"Conversations": "mypage.conversations",
	"Conversation": "mypage.conversation",
	"Conversation with agency": "mypage.conversationWithAgency",
	"No conversations yet. Message an agency to start chatting.": "mypage.noConversationsYetMessageAn",
	"Search conversations...": "mypage.searchConversations",
	"No conversations yet": "mypage.noConversationsYet",
	"No messages yet": "mypage.noMessagesYet",
	"When users message your agency, conversations will appear here. Make sure your agency profile is set up and verified.": "mypage.whenUsersMessageYourAgency",
	"Browse agencies and click Send message on their profile to start a conversation.": "mypage.browseAgenciesAndClickSend",
	"Browse agencies": "mypage.browseAgencies",
	"Select a conversation": "mypage.selectAConversation",
	"Choose a conversation from the left to start messaging": "mypage.chooseAConversationFromThe",
	"Block conversation": "mypage.blockConversation",
	"Block this conversation? You won't receive new messages.": "mypage.blockThisConversationYouWont",
	"You": "mypage.you",
	"edited": "mypage.edited",
	"Edit message": "mypage.editMessage",
	"This conversation is blocked": "mypage.thisConversationIsBlocked",
	"Type a message... (Enter to send, Shift+Enter for new line)": "mypage.typeAMessageEnterTo",
	"Application": "mypage.application",
	"Applied": "mypage.applied",
	"Payment": "mypage.payment",
	"Followed": "mypage.followed",
	"Agency account": "mypage.agencyAccount",
	"User account": "mypage.userAccount",
	"Agency management": "mypage.agencyManagement",
	"No cover photo": "mypage.noCoverPhoto",
	"Uploading...": "mypage.uploading",
	"Change cover photo": "mypage.changeCoverPhoto",
	"Add cover photo": "mypage.addCoverPhoto",
	"Click to change logo": "mypage.clickToChangeLogo",
	"Your agency is pending admin approval. You will be notified once verified.": "mypage.yourAgencyIsPendingAdmin",
	"Agency Information": "mypage.agencyInformation",
	"Agency name": "mypage.agencyName",
	"Comma-separated: Uzbekistan, Turkey, UAE": "mypage.commaSeparatedUzbekistanTurkeyUae",
	"Saving...": "mypage.saving",
	"No info added yet. Click Edit to fill in details.": "mypage.noInfoAddedYetClick",
	"Add to map": "mypage.addToMap",
	"Address": "mypage.address",
	"City/Country": "mypage.cityCountry",
	"No location set. Click Add to map to appear on the map.": "mypage.noLocationSetClickAdd",
	"City": "mypage.city",
	"Country (HQ)": "mypage.countryHq",
	"Latitude": "mypage.latitude",
	"Longitude": "mypage.longitude",
	"Save location": "mypage.saveLocation",
	"View public profile": "mypage.viewPublicProfile",
	"Register your agency on GMP. After submission, an admin will review and verify your profile.": "mypage.registerYourAgencyOnGmp",
	"Logo added - click to change": "mypage.logoAddedClickToChange",
	"Click circle to add logo": "mypage.clickCircleToAddLogo",
	"Business email": "mypage.businessEmail",
	"Register agency": "mypage.registerAgency",
	"Service catalog": "mypage.serviceCatalog",
	"My Services": "mypage.myServices",
	"New service": "mypage.newService",
	"Please register your agency first.": "mypage.pleaseRegisterYourAgencyFirst",
	"Your agency must be approved by a super admin before you can create services.": "mypage.yourAgencyMustBeApproved",
	"No services yet. Create your first service!": "mypage.noServicesYetCreateYour",
	"Edit service": "mypage.editService",
	"Create new service": "mypage.createNewService",
	"Service name": "mypage.serviceName",
	"Service type": "mypage.serviceType",
	"Destination country": "mypage.destinationCountry",
	"Source countries": "mypage.sourceCountries",
	"Comma-separated: Uzbekistan, Turkey": "mypage.commaSeparatedUzbekistanTurkey",
	"Price (USD)": "mypage.priceUsd",
	"Incoming requests": "mypage.incomingRequests",
	"Submitted": "mypage.submitted",
	"Under review": "mypage.underReview",
	"Completed": "mypage.completed",
	"No applications received yet.": "mypage.noApplicationsReceivedYet",
	"Complete": "mypage.complete",
	"Avatar updated!": "mypage.avatarUpdated",
	"Profile updated!": "mypage.profileUpdated",
	"Agency created! Pending admin approval.": "mypage.agencyCreatedPendingAdminApproval",
	"Location updated!": "mypage.locationUpdated",
	"Service updated!": "mypage.serviceUpdated",
	"Service created!": "mypage.serviceCreated",
	"Cover photo updated!": "mypage.coverPhotoUpdated",
	"Agency info updated!": "mypage.agencyInfoUpdated",
	"Logo updated!": "mypage.logoUpdated",
	"Live Now": "chat.liveNow",
	"Connecting...": "chat.connecting",
	"Community": "chat.community",
	"Live Chat": "chat.liveChat",
	"Online now": "chat.onlineNow",
	"Join to Chat": "chat.joinToChat",
	"Connect with travelers, students, and expats in real time. Ask questions, share experiences, and get instant answers from the GMP community.": "chat.connectWithTravelersStudentsAnd",
	"Global Chat": "chat.globalChat",
	"online": "chat.online",
	"No messages yet. Be the first!": "chat.noMessagesYetBeThe",
	"No messages yet. Say hi!": "chat.noMessagesYetSayHi",
	"Log in to chat": "chat.logInToChat",
	"Log in to join the conversation": "chat.logInToJoinThe",
	"Please enter a message!": "chat.pleaseEnterAMessage",
	"Chat is not connected!": "chat.chatIsNotConnected",
	"Guest": "chat.guest",
	"Contact Us": "help.contactUs",
	"Email": "help.email",
	"Phone": "help.phone",
	"Message": "help.message",
	"Support Center": "help.supportCenter",
	"How can we": "help.howCanWe",
	"help you?": "help.helpYou",
	"Search our knowledge base or browse topics below": "help.searchOurKnowledgeBaseOr",
	"Search for answers...": "help.searchForAnswers",
	"articles": "help.articles",
	"Frequently Asked Questions": "help.frequentlyAskedQuestions",
	"Quick answers to the most common questions": "help.quickAnswersToTheMost",
	"No results found for": "help.noResultsFoundFor",
	"Still need help?": "help.stillNeedHelp",
	"Our support team typically replies within a few hours.": "help.ourSupportTeamTypicallyReplies",
	"Office": "help.office",
	"Tashkent, Uzbekistan": "help.tashkentUzbekistan",
	"Working Hours": "help.workingHours",
	"Mon-Fri, 9:00-18:00": "help.monFri90018",
	"Verified Agencies": "help.verifiedAgencies",
	"Live Support": "help.liveSupport",
	"Send us a message": "help.sendUsAMessage",
	"We'll get back to you as soon as possible": "help.wellGetBackToYou",
	"Your name": "help.yourName",
	"Email address": "help.emailAddress",
	"Describe your issue or question...": "help.describeYourIssueOrQuestion",
	"Send Message": "help.sendMessage",
	"Failed to send message": "help.failedToSendMessage",
	"Message sent! We'll get back to you within 24 hours.": "help.messageSentWellGetBack",
	"Support": "legal.support",
	"About GMP": "legal.aboutGmp",
	"Legal": "legal.legal",
	"All Services": "footer.allServices",
	"Global Migration Platform - connecting people with trusted immigration and travel agencies worldwide.": "footer.globalMigrationPlatformConnectingPeople",
	"Global Migration Platform. All rights reserved.": "footer.globalMigrationPlatformAllRights",
	"Company": "footer.company",
	"Account": "footer.account",
	"Agency Map": "footer.agencyMap",
	"About Us": "footer.aboutUs",
	"Sign In": "footer.signIn",
	"My Profile": "footer.myProfile",
	"Stay Updated": "footer.stayUpdated",
	"Get the latest migration news and service updates directly to your inbox.": "footer.getTheLatestMigrationNews",
	"Your email address": "footer.yourEmailAddress",
	"Subscribe": "footer.subscribe",
	"Secure": "footer.secure",
	"Clients Served": "footer.clientsServed",
	"Privacy Policy": "footer.privacyPolicy",
	"Terms of Service": "footer.termsOfService",
	"Cookies": "footer.cookies",
	"Contact": "footer.contact",
	"Logout": "admin.logout",
	"Verified": "admin.verified",
	"services": "admin.services",
	"Overview": "admin.overview",
	"Management": "admin.management",
	"System": "admin.system",
	"Management Panel": "admin.managementPanel",
	"Dashboard": "admin.dashboard",
	"Audit Log": "admin.auditLog",
	"Super Admin": "admin.superAdmin",
	"Language updated": "admin.languageUpdated",
	"Failed to update language": "admin.failedToUpdateLanguage",
	"Users Management": "admin.usersManagement",
	"Agencies Management": "admin.agenciesManagement",
	"Services Management": "admin.servicesManagement",
	"Reviews Moderation": "admin.reviewsModeration",
	"Support Messages": "admin.supportMessages",
	"Search name / email / phone": "admin.searchNameEmailPhone",
	"Search by name / email": "admin.searchByNameEmail",
	"Search by service name": "admin.searchByServiceName",
	"Search name, email, message": "admin.searchNameEmailMessage",
	"All statuses": "admin.allStatuses",
	"All roles": "admin.allRoles",
	"All verifications": "admin.allVerifications",
	"All types": "admin.allTypes",
	"All reviews": "admin.allReviews",
	"Total": "admin.total",
	"Total actions": "admin.totalActions",
	"Name": "admin.name",
	"Role": "admin.role",
	"Joined": "admin.joined",
	"Created": "admin.created",
	"Actions": "admin.actions",
	"Action": "admin.action",
	"Target": "admin.target",
	"Target Type": "admin.targetType",
	"Reason": "admin.reason",
	"Date & Time": "admin.dateTime",
	"Type": "admin.type",
	"Verification": "admin.verification",
	"Visibility": "admin.visibility",
	"Comment": "admin.comment",
	"Date": "admin.date",
	"Hide": "admin.hide",
	"Ban": "admin.ban",
	"Unban": "admin.unban",
	"Delete": "admin.delete",
	"Close": "admin.close",
	"Refresh": "admin.refresh",
	"Submit": "admin.submit",
	"Activate": "admin.activate",
	"Suspend": "admin.suspend",
	"Archive": "admin.archive",
	"Open": "admin.open",
	"Resolve": "admin.resolve",
	"In progress": "admin.inProgress",
	"No users found": "admin.noUsersFound",
	"No reviews found.": "admin.noReviewsFound",
	"Loading reviews...": "admin.loadingReviews",
	"No support messages found": "admin.noSupportMessagesFound",
	"No actions recorded yet": "admin.noActionsRecordedYet",
	"User banned": "admin.userBanned",
	"User unbanned": "admin.userUnbanned",
	"Agency approved!": "admin.agencyApproved",
	"Agency rejected": "admin.agencyRejected",
	"Agency suspended": "admin.agencySuspended",
	"Agency activated": "admin.agencyActivated",
	"Agency deleted": "admin.agencyDeleted",
	"Service status updated": "admin.serviceStatusUpdated",
	"Review approved": "admin.reviewApproved",
	"Review rejected": "admin.reviewRejected",
	"Review hidden": "admin.reviewHidden",
	"Support ticket updated": "admin.supportTicketUpdated",
	"Failed to update review": "admin.failedToUpdateReview",
	"Ban this user?": "admin.banThisUser",
	"Unban this user?": "admin.unbanThisUser",
	"Approve this agency?": "admin.approveThisAgency",
	"Suspend this agency? Users will not see it.": "admin.suspendThisAgencyUsersWill",
	"Activate this agency?": "admin.activateThisAgency",
	"Active": "admin.active",
	"Banned": "admin.banned",
	"Inactive": "admin.inactive",
	"Suspended": "admin.suspended",
	"Pending": "admin.pending",
	"Draft": "admin.draft",
	"Archived": "admin.archived",
	"Resolved": "admin.resolved",
	"Agency Admin": "admin.agencyAdmin",
	"selected": "admin.selected",
	"users banned": "admin.usersBanned",
	"Ban all selected": "admin.banAllSelected",
	"Ban all": "admin.banAll",
	"Clear": "admin.clear",
	"User Profile": "admin.userProfile",
	"Permanently delete": "admin.permanentlyDelete",
	"This cannot be undone.": "admin.thisCannotBeUndone",
	"Services / Reviews": "admin.servicesReviews",
	"Registered": "admin.registered",
	"Operating Countries": "admin.operatingCountries",
	"Rejection reason": "admin.rejectionReason",
	"Explain why this agency is being rejected...": "admin.explainWhyThisAgencyIs",
	"Failed to update": "admin.failedToUpdate",
	"Free": "admin.free",
	"Service ID": "admin.serviceId",
	"No comment": "admin.noComment",
	"Reject review": "admin.rejectReview",
	"Hide review": "admin.hideReview",
	"Total Users": "admin.totalUsers",
	"Total Agencies": "admin.totalAgencies",
	"Total Services": "admin.totalServices",
	"Apps": "admin.apps",
	"Subscr.": "admin.subscr",
	"Verif.": "admin.verif",
	"Active Subscriptions": "admin.activeSubscriptions",
	"Pending Verifications": "admin.pendingVerifications",
	"Total Records": "admin.totalRecords",
	"Platform Statistics": "admin.platformStatistics",
	"Distribution": "admin.distribution",
	"Ban User": "admin.banUser",
	"Unban User": "admin.unbanUser",
	"Delete User": "admin.deleteUser",
	"Approve Agency": "admin.approveAgency",
	"Reject Agency": "admin.rejectAgency",
	"Suspend Agency": "admin.suspendAgency",
	"Activate Agency": "admin.activateAgency",
	"Delete Agency": "admin.deleteAgency",
	"Chat": "common.chat",
	"Top 5 agencies": "common.top5Agencies",
	"Save": "common.save",
	"GMP helps people compare migration, study, work, travel, and visa services from agencies in one place.": "common.gMPHelpsPeopleCompareMigration",
	"The platform is built around verified agency profiles, searchable service listings, application tracking, and direct messaging.": "common.thePlatformIsBuiltAround",
	"What We Focus On": "common.whatWeFocusOn",
	"Clear agency profiles and service information.": "common.clearAgencyProfilesAndService",
	"Simple communication between users and agencies.": "common.simpleCommunicationBetweenUsersAnd",
	"Admin verification before agencies appear publicly.": "common.adminVerificationBeforeAgenciesAppear",
	"GMP stores account, agency, service, application, and messaging data needed to operate the platform.": "common.gMPStoresAccountAgencyService",
	"Uploaded files and profile images are used only for account, agency, and application workflows.": "common.uploadedFilesAndProfileImages",
	"Your Choices": "common.yourChoices",
	"You can update your profile from My Page.": "common.youCanUpdateYourProfile",
	"You can contact support for account or data questions.": "common.youCanContactSupportFor",
	"Agency data may require admin review before appearing publicly.": "common.agencyDataMayRequireAdmin",
	"By using GMP, users and agencies agree to provide accurate information and use the platform responsibly.": "common.byUsingGmpUsersAnd",
	"Agencies are responsible for keeping service information, pricing, processing time, and contact details current.": "common.agenciesAreResponsibleForKeeping",
	"Platform Rules": "common.platformRules",
	"False or misleading agency information may be rejected or removed.": "common.falseOrMisleadingAgencyInformation",
	"Messages and applications should relate to legitimate service requests.": "common.messagesAndApplicationsShouldRelate",
	"Admin actions may restrict accounts, agencies, or services when needed.": "common.adminActionsMayRestrictAccounts",
	"GMP uses browser storage to keep users signed in, remember language preference, and support core app behavior.": "common.gMPUsesBrowserStorageTo",
	"Authentication tokens and language settings are stored locally in the browser.": "common.authenticationTokensAndLanguageSettings",
	"Managing Storage": "common.managingStorage",
	"You can clear browser storage or sign out to remove local session data from your device.": "common.youCanClearBrowserStorage",
	"For account, agency verification, application, or service questions, contact the GMP support team.": "common.forAccountAgencyVerificationApplication",
	"UAE": "enum.UAE",
	"OPEN": "enum.OPEN",
	"IN_PROGRESS": "enum.IN_PROGRESS",
	"RESOLVED": "enum.RESOLVED",
	"ACTIVE": "enum.ACTIVE",
	"BANNED": "enum.BANNED",
	"INACTIVE": "enum.INACTIVE",
	"SUSPENDED": "enum.SUSPENDED",
	"PENDING": "enum.PENDING",
	"VERIFIED": "enum.VERIFIED",
	"REJECTED": "enum.REJECTED",
	"APPROVED": "enum.APPROVED",
	"HIDDEN": "enum.HIDDEN",
	"DRAFT": "enum.DRAFT",
	"ARCHIVED": "enum.ARCHIVED",
	"PUBLIC": "enum.PUBLIC",
	"AGENCY_ONLY": "enum.AGENCY_ONLY",
	"USER": "enum.USER",
	"AGENCY_ADMIN": "enum.AGENCY_ADMIN",
	"SUPER_ADMIN": "enum.SUPER_ADMIN",
	"GUEST": "enum.GUEST",
	"VISA_SERVICES": "enum.VISA_SERVICES",
	"STUDY_ABROAD": "enum.STUDY_ABROAD",
	"WORK_ABROAD": "enum.WORK_ABROAD",
	"TRAVEL": "enum.TRAVEL",
};
