export enum ApplicationStatus {
	SUBMITTED = 'SUBMITTED',
	UNDER_REVIEW = 'UNDER_REVIEW',
	APPROVED = 'APPROVED',
	REJECTED = 'REJECTED',
	ACCEPTED = 'ACCEPTED',
	COMPLETED = 'COMPLETED',
	WITHDRAWN = 'WITHDRAWN',
}

export enum PaymentStatus {
	PENDING = 'PENDING',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	REFUNDED = 'REFUNDED',
}
